package routes

import (
	"github.com/gin-gonic/gin"

	"github.com/AeolianCloud/pveCloud/server/internal/app/api"
	"github.com/AeolianCloud/pveCloud/server/internal/delivery/http/admin/middleware"
)

/**
 * RegisterAdminRoutes 注册管理端 API 路由。
 *
 * @param group 管理端路由分组
 * @param app API 应用依赖容器
 */
func RegisterAdminRoutes(group *gin.RouterGroup, app *api.App) {
	routes := app.Routes.Admin

	admin := group.Group("")
	admin.Use(middleware.AdminAuditContext())
	admin.GET("/ping", routes.System.Ping)
	admin.GET("/auth/captcha", routes.Auth.Captcha)
	admin.POST("/auth/login", routes.Auth.Login)
	admin.POST("/client-logs/errors", routes.ClientLogs.Create)

	protected := admin.Group("")
	protected.Use(routes.AuthMiddleware)
	protected.GET("/auth/me", routes.Auth.Me)
	protected.POST("/auth/logout", routes.Auth.Logout)
	protected.POST("/auth/refresh", routes.Auth.Refresh)
	protected.GET("/dashboard", middleware.AdminPermission("page.dashboard"), routes.Dashboard.Show)
	protected.GET("/admin-users", middleware.AdminPermission("page.system-settings.admin-users"), routes.AdminUser.List)
	protected.POST("/admin-users", middleware.AdminPermission("admin-user:create"), routes.AdminUser.Create)
	protected.GET("/admin-users/:id", middleware.AdminPermission("page.system-settings.admin-users"), routes.AdminUser.Detail)
	protected.PATCH("/admin-users/:id", middleware.AdminPermission("admin-user:update"), routes.AdminUser.Update)
	protected.POST("/admin-users/:id/password", middleware.AdminPermission("admin-user:password-reset"), routes.AdminUser.ResetPassword)
	protected.GET("/admin-roles", middleware.AdminPermission("page.system-settings.admin-roles"), routes.AdminRole.Roles)
	protected.POST("/admin-roles", middleware.AdminPermission("admin-role:create"), routes.AdminRole.CreateRole)
	protected.GET("/admin-roles/:id", middleware.AdminPermission("page.system-settings.admin-roles"), routes.AdminRole.RoleDetail)
	protected.PATCH("/admin-roles/:id", middleware.AdminPermission("admin-role:update"), routes.AdminRole.UpdateRole)
	protected.GET("/admin-permissions", middleware.AdminPermission("page.system-settings.admin-roles"), routes.AdminRole.Permissions)
	protected.GET("/admin-sessions", middleware.AdminPermission("page.system-settings.admin-sessions"), routes.AdminSession.List)
	protected.PATCH("/admin-sessions/:session_id", middleware.AdminPermission("admin-session:revoke"), routes.AdminSession.Update)
	protected.GET("/audit-logs", middleware.AdminAnyPermission("page.logs.admin-operations", "page.logs.admin-security", "page.system-settings.audit-logs"), routes.Audit.Logs)
	protected.GET("/logs/user-security", middleware.AdminPermission("page.logs.user-security", "user-security-log:view"), routes.Logs.UserSecurity)
	protected.GET("/logs/user-business", middleware.AdminPermission("page.logs.user-business", "user-business-log:view"), routes.Logs.UserBusiness)
	protected.GET("/logs/frontend-errors", middleware.AdminPermission("page.logs.frontend-errors", "frontend-error-log:view"), routes.Logs.FrontendErrors)
	protected.GET("/logs/backend-runtime", middleware.AdminPermission("page.logs.backend-runtime", "backend-runtime-log:view"), routes.Logs.BackendRuntime)
	protected.GET("/system-configs", middleware.AdminPermission("page.system-settings.config"), routes.SystemConfig.Configs)
	protected.PATCH("/system-configs/:id", middleware.AdminPermission("system-config:update"), routes.SystemConfig.Update)
	protected.GET("/users", middleware.AdminPermission("page.web-users"), routes.WebUser.Users)
	protected.POST("/users", middleware.AdminPermission("web-user:create"), routes.WebUser.CreateUser)
	protected.GET("/users/:id", middleware.AdminPermission("page.web-users"), routes.WebUser.UserDetail)
	protected.PATCH("/users/:id", middleware.AdminPermission("web-user:update"), routes.WebUser.UpdateUser)
	protected.POST("/users/:id/password", middleware.AdminPermission("web-user:password-reset"), routes.WebUser.ResetPassword)
	protected.GET("/user-sessions", middleware.AdminPermission("page.web-user-sessions"), routes.WebUser.Sessions)
	protected.PATCH("/user-sessions/:session_id", middleware.AdminPermission("web-user-session:revoke"), routes.WebUser.RevokeSession)
	protected.GET("/real-name-applications", middleware.AdminPermission("page.real-name-management"), routes.RealName.Applications)
	protected.GET("/real-name-applications/:id", middleware.AdminPermission("page.real-name-management"), routes.RealName.Detail)
	protected.POST("/real-name-applications/:id/sync", middleware.AdminPermission("real-name:sync"), routes.RealName.Sync)
	protected.POST("/real-name-applications/:id/review", middleware.AdminPermission("real-name:review"), routes.RealName.Review)
	protected.GET("/products", middleware.AdminPermission("page.products"), routes.ProductCatalog.Products)
	protected.POST("/products", middleware.AdminPermission("product:create"), routes.ProductCatalog.CreateProduct)
	protected.PUT("/products/:id", middleware.AdminPermission("product:update"), routes.ProductCatalog.UpdateProduct)
	protected.PATCH("/products/:id/status", middleware.AdminPermission("product:publish"), routes.ProductCatalog.UpdateProductStatus)
	protected.DELETE("/products/:id", middleware.AdminPermission("product:delete"), routes.ProductCatalog.DeleteProduct)
	protected.GET("/product-plans", middleware.AdminPermission("page.products"), routes.ProductCatalog.Plans)
	protected.POST("/product-plans", middleware.AdminPermission("product:create"), routes.ProductCatalog.CreatePlan)
	protected.PUT("/product-plans/:id", middleware.AdminPermission("product:update"), routes.ProductCatalog.UpdatePlan)
	protected.PATCH("/product-plans/:id/status", middleware.AdminPermission("product:publish"), routes.ProductCatalog.UpdatePlanStatus)
	protected.DELETE("/product-plans/:id", middleware.AdminPermission("product:delete"), routes.ProductCatalog.DeletePlan)
	protected.GET("/product-plans/:id/prices", middleware.AdminPermission("page.products"), routes.ProductCatalog.PlanPrices)
	protected.PUT("/product-plans/:id/prices", middleware.AdminPermission("product:update"), routes.ProductCatalog.UpdatePlanPrices)
	protected.GET("/product-plans/:id/regions", middleware.AdminPermission("page.products"), routes.ProductCatalog.PlanRegions)
	protected.PUT("/product-plans/:id/regions", middleware.AdminPermission("product:update"), routes.ProductCatalog.UpdatePlanRegions)
	protected.GET("/product-plans/:id/os-templates", middleware.AdminPermission("page.products"), routes.ProductCatalog.PlanOSTemplates)
	protected.PUT("/product-plans/:id/os-templates", middleware.AdminPermission("product:update"), routes.ProductCatalog.UpdatePlanOSTemplates)
	protected.GET("/product-plans/:id/network-types", middleware.AdminPermission("page.products"), routes.ProductCatalog.PlanNetworkTypes)
	protected.PUT("/product-plans/:id/network-types", middleware.AdminPermission("product:update"), routes.ProductCatalog.UpdatePlanNetworkTypes)
	protected.GET("/sales-regions", middleware.AdminPermission("page.products"), routes.ProductCatalog.SalesRegions)
	protected.POST("/sales-regions", middleware.AdminPermission("product:create"), routes.ProductCatalog.CreateSalesRegion)
	protected.PUT("/sales-regions/:id", middleware.AdminPermission("product:update"), routes.ProductCatalog.UpdateSalesRegion)
	protected.DELETE("/sales-regions/:id", middleware.AdminPermission("product:delete"), routes.ProductCatalog.DeleteSalesRegion)
	protected.GET("/server-os-templates", middleware.AdminPermission("page.products"), routes.ProductCatalog.ServerOSTemplates)
	protected.POST("/server-os-templates", middleware.AdminPermission("product:create"), routes.ProductCatalog.CreateServerOSTemplate)
	protected.PUT("/server-os-templates/:id", middleware.AdminPermission("product:update"), routes.ProductCatalog.UpdateServerOSTemplate)
	protected.DELETE("/server-os-templates/:id", middleware.AdminPermission("product:delete"), routes.ProductCatalog.DeleteServerOSTemplate)
	protected.GET("/network-types", middleware.AdminPermission("page.products"), routes.ProductCatalog.NetworkTypes)
	protected.POST("/network-types", middleware.AdminPermission("product:create"), routes.ProductCatalog.CreateNetworkType)
	protected.PUT("/network-types/:id", middleware.AdminPermission("product:update"), routes.ProductCatalog.UpdateNetworkType)
	protected.DELETE("/network-types/:id", middleware.AdminPermission("product:delete"), routes.ProductCatalog.DeleteNetworkType)
	protected.GET("/orders", middleware.AdminPermission("page.orders"), routes.Order.List)
	protected.GET("/orders/:order_no", middleware.AdminPermission("page.orders"), routes.Order.Detail)
	protected.PATCH("/orders/:order_no/admin-note", middleware.AdminPermission("order:update"), routes.Order.UpdateAdminNote)
	protected.POST("/orders/:order_no/cancel", middleware.AdminPermission("order:cancel"), routes.Order.Cancel)
	protected.POST("/orders/:order_no/close", middleware.AdminPermission("order:update"), routes.Order.Close)
	protected.POST("/orders/:order_no/provision", middleware.AdminPermission("instance:provision"), routes.Instance.ProvisionOrder)
	protected.GET("/instance-provision-mappings", middleware.AdminPermission("page.instances"), routes.Instance.Mappings)
	protected.POST("/instance-provision-mappings", middleware.AdminPermission("instance:provision"), routes.Instance.CreateMapping)
	protected.PATCH("/instance-provision-mappings/:id", middleware.AdminPermission("instance:provision"), routes.Instance.UpdateMapping)
	protected.GET("/mcp-pve/nodes", middleware.AdminPermission("page.instances"), routes.Instance.Nodes)
	protected.GET("/mcp-pve/nodes/:node", middleware.AdminPermission("page.instances"), routes.Instance.Node)
	protected.GET("/mcp-pve/nodes/:node/vms", middleware.AdminPermission("page.instances"), routes.Instance.NodeVMs)
	protected.GET("/mcp-pve/storage", middleware.AdminPermission("page.instances"), routes.Instance.Storage)
	protected.GET("/instances", middleware.AdminPermission("page.instances"), routes.Instance.List)
	protected.GET("/instances/:instance_no", middleware.AdminPermission("page.instances"), routes.Instance.Detail)
	protected.POST("/instances/:instance_no/start", middleware.AdminPermission("instance:operate"), routes.Instance.Start)
	protected.POST("/instances/:instance_no/stop", middleware.AdminPermission("instance:operate"), routes.Instance.Stop)
	protected.POST("/instances/:instance_no/release", middleware.AdminPermission("instance:release"), routes.Instance.Release)
	protected.POST("/instances/:instance_no/sync", middleware.AdminPermission("instance:sync"), routes.Instance.Sync)
	protected.GET("/tickets", middleware.AdminPermission("page.tickets"), routes.Ticket.List)
	protected.GET("/tickets/assignee-candidates", middleware.AdminPermission("ticket:assign"), routes.Ticket.AssigneeCandidates)
	protected.GET("/tickets/:ticket_no", middleware.AdminPermission("page.tickets"), routes.Ticket.Detail)
	protected.POST("/tickets/:ticket_no/messages", middleware.AdminPermission("ticket:reply"), routes.Ticket.Reply)
	protected.POST("/tickets/:ticket_no/close", middleware.AdminPermission("ticket:close"), routes.Ticket.Close)
	protected.POST("/tickets/:ticket_no/assign", middleware.AdminPermission("ticket:assign"), routes.Ticket.Assign)
	protected.POST("/tickets/:ticket_no/collaborators", middleware.AdminPermission("ticket:collaborate"), routes.Ticket.AddCollaborator)
	protected.DELETE("/tickets/:ticket_no/collaborators/:admin_id", middleware.AdminPermission("ticket:collaborate"), routes.Ticket.RemoveCollaborator)
	protected.POST("/tickets/:ticket_no/internal-notes", middleware.AdminPermission("ticket:note"), routes.Ticket.AddInternalNote)
	protected.POST("/tickets/:ticket_no/priority", middleware.AdminPermission("ticket:priority"), routes.Ticket.UpgradePriority)
	protected.PUT("/tickets/:ticket_no/tags", middleware.AdminPermission("ticket:tag"), routes.Ticket.ReplaceTags)
	protected.GET("/tickets/:ticket_no/attachments/:file_id/download", middleware.AdminPermission("page.tickets"), routes.Ticket.Download)
	protected.GET("/ticket-tags", middleware.AdminPermission("page.tickets"), routes.Ticket.Tags)
	protected.POST("/ticket-tags", middleware.AdminPermission("ticket:tag-manage"), routes.Ticket.CreateTag)
	protected.PATCH("/ticket-tags/:id", middleware.AdminPermission("ticket:tag-manage"), routes.Ticket.UpdateTag)
	protected.POST("/files/upload", middleware.AdminPermission("file:upload"), routes.FileAttachment.Upload)
	protected.GET("/files", middleware.AdminPermission("page.file-management"), routes.FileAttachment.List)
	protected.GET("/files/:id", middleware.AdminPermission("page.file-management"), routes.FileAttachment.Detail)
	protected.GET("/files/:id/download", middleware.AdminPermission("page.file-management"), routes.FileAttachment.Download)
	protected.GET("/files/:id/references", middleware.AdminPermission("page.file-management"), routes.FileAttachment.Reference)
	protected.DELETE("/files/:id", middleware.AdminPermission("file:delete"), routes.FileAttachment.Delete)
}
