#!/usr/bin/env node

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptPath = fileURLToPath(import.meta.url);
const repoRoot = path.resolve(path.dirname(scriptPath), '..');
const srcRoot = path.join(repoRoot, 'docs/server/api/openapi-src');
const rootPath = path.join(srcRoot, 'root.yaml');
const pathsDir = path.join(srcRoot, 'paths');
const schemasDir = path.join(srcRoot, 'schemas');
const outputPath = path.join(repoRoot, 'docs/server/api/openapi.yaml');
const checkOnly = process.argv.includes('--check');

validateInput();

const generatedHeader = [
  '# This file is generated by scripts/generate-openapi.mjs. Do not edit manually.',
  '# Edit docs/server/api/openapi-src/ and regenerate this file.',
  '',
].join('\n');

const rootTemplate = stripLeadingCommentBlock(readText(rootPath));
const paths = readFragments(pathsDir);
const schemas = readFragments(schemasDir);
const output = (generatedHeader + rootTemplate)
  .replace('{{paths}}', paths)
  .replace('{{schemas}}', schemas)
  .replace(/\r\n/g, '\n')
  .replace(/\n*$/, '\n');

if (checkOnly) {
  const current = existsSync(outputPath) ? readText(outputPath).replace(/\n*$/, '\n') : '';
  if (current !== output) {
    console.error('[openapi] docs/server/api/openapi.yaml 不是最新生成结果，请运行：node ./scripts/generate-openapi.mjs');
    process.exit(1);
  }
  console.log('[openapi] openapi.yaml 已是最新生成结果。');
  process.exit(0);
}

writeFileSync(outputPath, output, 'utf8');
console.log('[openapi] 已生成 docs/server/api/openapi.yaml');

function validateInput() {
  for (const requiredPath of [rootPath, pathsDir, schemasDir]) {
    if (!existsSync(requiredPath)) {
      console.error(`[openapi] 缺少生成源：${path.relative(repoRoot, requiredPath)}`);
      process.exit(1);
    }
  }
}

function readFragments(dir) {
  return readdirSync(dir)
    .filter((name) => name.endsWith('.yaml') || name.endsWith('.yml'))
    .sort((left, right) => left.localeCompare(right))
    .map((name) => readText(path.join(dir, name)).replace(/\n*$/, ''))
    .join('\n');
}

function readText(filePath) {
  return readFileSync(filePath, 'utf8').replace(/\r\n/g, '\n');
}

function stripLeadingCommentBlock(text) {
  const lines = text.split('\n');
  while (lines.length > 0 && lines[0].startsWith('#')) {
    lines.shift();
  }
  return lines.join('\n').replace(/^\n+/, '');
}
